name = "packageexample"
uuid = "4ec59724-bd80-486e-b9ec-b0e0be6a6029"
authors = ["Kevin F. Garrity"]
version = "0.1.0"

[compat]
julia = "1"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
